GET http://localhost:8082/main?firstname=TESTUSER1&surname=TESTUSER1&patronymic=Отчество&driverID=QWERTY-12&controlValue=9b07a6ac327e8dd7d948ffe65b4bfe853c916a0c93b4b1b37b8660311e70c725
Accept: application/json

###

GET http://localhost:8082/main?controlValue=9b07a6ac327e8dd7d948ffe65b4bfe853c916a0c93b4b1b37b8660311e70c725&firstname=TESTUSER1&surname=TESTUSER1&patronymic=Отчество&driverID=QWERTY-12
Accept: application/json

##