GET http://localhost:8082/main?firstname=TESTUSER1&surname=TESTUSER1&patronymic=Patronymic&driverID=QWERTY-12&findRelatives=1&controlValue=07a136faaef4688e36af29af2805ad9b821feb503d013728883bf4e4dd2e10a2
Accept: application/json

###

GET http://localhost:8082/main?controlValue=07a136faaef4688e36af29af2805ad9b821feb503d013728883bf4e4dd2e10a2&firstname=TESTUSER1&surname=TESTUSER1&patronymic=Отчество&driverID=QWERTY-12
Accept: application/json

##